services:
- type: web
  name: ledger:v1.10.0
  runtime: image
  image:
    url: ghcr.io/formancehq/ledger:v1.10.0
  plan: starter
  envVars:
  - key: PORT
    value: 3068
  - key: NUMARY_STORAGE_POSTGRES_CONN_STRING
    sync: postgres://ledger:v5OiPDDurdy9LiCIrgk3RJUBPuX4j52l@dpg-cp1aft021fec739bi110-a/ledger_m2zk
  - key: NUMARY_STORAGE_DRIVER
    sync: postgres
  - key: NUMARY_UI_HTTP_BIND_ADDRESS
    value: 0.0.0.0:3068
  - key: NUMARY_SERVER_HTTP_BIND_ADDRESS
    sync: 0.0.0.0:3068
  region: ohio
version: "1"

databases:
  - name: ledger-database
    plan: standard
    databaseName: ledger
    postgresMajorVersion: 15
    user: ledger
