services:
  - type: web
    name: ledger
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    startCommand: go run main.go serve
    envVars:
      - key: STORAGE_DRIVER
        value: postgres
      - key: STORAGE_POSTGRES_CONN_STRING
        value: postgresql://ledger:ledger@postgres/ledger?sslmode=disable
      - key: DEBUG
        value: 'true'
      - key: DATABASE_URL
        fromDatabase:
          name: ledger-database
          property: connectionString

    healthCheckPath: /
    dockerContext: /src

databases:
  - name: ledger-database
    plan: standard
    databaseName: ledger
    postgresMajorVersion: 15
    user: ledger
